# Generated by Django 2.2.6 on 2020-01-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20200119_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={},
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='slug',
        ),
    ]
