# Generated by Django 2.2.6 on 2020-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20200119_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypost',
            name='image',
            field=models.ImageField(blank=True, upload_to='session/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, upload_to='session/%Y/%m/%d'),
        ),
    ]
