# Generated by Django 2.2.6 on 2020-02-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20200201_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, upload_to='session/news'),
        ),
    ]
