# Generated by Django 2.2.6 on 2020-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20200201_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='activitypost',
            name='image',
            field=models.ImageField(blank=True, upload_to='session/activity'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
