# Generated by Django 2.2.6 on 2020-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20200201_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
