# Generated by Django 2.2.6 on 2020-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20200201_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
