# Generated by Django 2.2.6 on 2020-02-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_newspost_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-publish_date', '-updated']},
        ),
    ]
