# Generated by Django 2.2.6 on 2020-02-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_auto_20200202_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
