# Generated by Django 3.0.1 on 2020-01-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200117_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_main_image',
        ),
    ]
