# Generated by Django 3.0.1 on 2020-01-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_project_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
