# Generated by Django 3.0.1 on 2020-01-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200117_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_main_image',
            field=models.ImageField(blank=True, upload_to='project_main_image/'),
        ),
    ]
